Weekly meetings are held on Fridays (PST)/ Saturdays (AEDT)

-----------------------------
# 25 July:

Visalization in accouting:

1. application of 

2. balancesheet representation
dashboard with different presentation

prediction based on 

where to go

task: exact task to complete and timeline

3. definition - criteria for pickng up packages:

applicability to accounting

list package
general discussion of packages
future directions

Tasks: select packages for paper

-----------------------------

# 4 July:

To do list:

1. finalize and publish "insurance" tutorial - Maria/ Felix to fix leftovers

2. review the structure of the paper "Landscape of accounting in the R universe" - Maria to set up and build / Felix to review

3. 3 Packages to consider development: - both to explore

- reconcilliation 

- VizAccR

- XBRL and working with external public data

Consider applying for RStudio grant for funding to provide internships to students: Maria to explore
Felix to consider and review

Felix to get in touch with Melody to get testing files

4. Review topics for CPA Australia discussion group - Maria to setup/ Felix to review
Felix to present in August, the CPA meeting to be moved to lunch time
Maria to present in July, Felix to attend
Consider engaging students - Maria to explore

report: Maria discussed with students - they are happy to prepare


-----------------------------

February:

Tasks to do:
1. Landscape business application and tasks and relate the to R packages and R tutorials
2. Start drafting the task view for RBusiness
3. Identify particular projects to work on


Outcomes:
Landscape document is work in progress

=======================================

**March 28**

Discussed APIs to retrieve financial data (accounting statements):
Options: US Sec. UK Company


